# Generated by Django 3.0.6 on 2020-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_mahasiswa',
            fields=[
                ('npm', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'dt_mahasiswa',
            },
        ),
    ]
